version: '3.4'

volumes:
  db-data: {}

services:
  users:
    build: ./users
    depends_on:
      - db
    volumes:
      - ./users:/users
    environment:
      - DB_HOST
      - DB_PORT=${DB_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"

  db:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data:rw
  adminer:
    image: adminer
    ports:
      - 8080:8080